service: streaming-playground-api

package:
  individually: true

plugins:
- serverless-dynamodb-local
- serverless-bundle # Package our functions with Webpack
- serverless-offline
- serverless-dotenv-plugin # Load .env as environment variables

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  websocketConnectionsTableName: streaming-playground-${self:custom.stage}-websocket-sessions
  openTokEventsTableName: streaming-playground-${self:custom.stage}-opentok-events
  userProfilesTableName: streaming-playground-${self:custom.stage}-user-profiles
  poolsTableName: streaming-playground-${self:custom.stage}-pools
  streamsTableName: streaming-playground-${self:custom.stage}-streams
  dynamodb:
    stages:
    - offline
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  logs:
    websocket: true
    restApi: true
  environment:
    websocketConnectionsTableName: ${self:custom.websocketConnectionsTableName}
    openTokEventsTableName: ${self:custom.openTokEventsTableName}
    userProfilesTableName: ${self:custom.userProfilesTableName}
    poolsTableName: ${self:custom.poolsTableName}
    streamsTableName: ${self:custom.streamsTableName}
    openTokApiKey: ${env:OPEN_TOK_API_KEY}
    openTokSecret: ${env:OPEN_TOK_SECRET}
    stripeSecretKey: ${env:STRIPE_SECRET_KEY}

  iamRoleStatements:
  - Effect: Allow
    Action:
    - dynamodb:DescribeTable
    - dynamodb:Query
    - dynamodb:Scan
    - dynamodb:GetItem
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem
    Resource:
    - "Fn::GetAtt": [ WebsocketConnectionsTable, Arn ]
    - "Fn::GetAtt": [ UserProfilesTable, Arn ]
    - "Fn::GetAtt": [ PoolsTable, Arn ]
    - "Fn::GetAtt": [ StreamsTable, Arn ]
  - Effect: Allow
    Action:
    - execute-api:Invoke
    Resource:
    - "Fn::Join": ["", ["arn:aws:execute-api:",{"Ref":"AWS::Region"},":",{"Ref":"AWS::AccountId"},":",{"Ref":"ApiGatewayRestApi"},"/${self:custom.stage}/*"]]

functions:
  websocket-handler:
    handler: api/websocket/handler.main
    events:
    - websocket:
        route: $connect
        cors: true
    - websocket:
        route: $disconnect
        cors: true
    - websocket:
        route: enterPool
        cors: true
    - websocket:
        route: exitPool
        cors: true

  opentok-callback:
    handler: api/opentok/callback.main
    events:
    - http:
        path: opentok/callback
        method: post
        cors: true
        authorizer: aws_iam

  user-profile:
    handler: api/user/profile.main
    events:
    - http:
        path: user/profile
        method: get
        cors: true
        authorizer: aws_iam

  streams-list:
    handler: api/streams/list.main
    events:
    - http:
        path: pools/{poolId}/streams
        method: get
        cors: true
        authorizer: aws_iam

  streams-get:
    handler: api/streams/get.main
    events:
    - http:
        path: pools/{poolId}/streams/{streamId}
        method: get
        cors: true
        authorizer: aws_iam

  streams-start:
    handler: api/streams/start.main
    events:
    - http:
        path: pools/{poolId}/streams
        method: post
        cors: true
        authorizer: aws_iam

  streams-stop:
    handler: api/streams/stop.main
    events:
    - http:
        path: pools/{poolId}/streams/{streamId}
        method: delete
        cors: true
        authorizer: aws_iam

  streams-update:
    handler: api/streams/update.main
    events:
    - http:
        path: pools/{poolId}/streams/{streamId}
        method: put
        cors: true
        authorizer: aws_iam

  pools-create:
    handler: api/pools/create.main
    events:
    - http:
        path: pools
        method: post
        cors: true
        authorizer: aws_iam

  pools-get:
    handler: api/pools/get.main
    events:
    - http:
        path: pools/{poolId}
        method: get
        cors: true
        authorizer: aws_iam

  pools-list:
    handler: api/pools/list.main
    events:
    - http:
        path: pools
        method: get
        cors: true
        authorizer: aws_iam

  pools-update:
    handler: api/pools/update.main
    events:
    - http:
        path: pools/{poolId}
        method: put
        cors: true
        authorizer: aws_iam

  pools-delete:
    handler: api/pools/delete.main
    events:
    - http:
        path: pools/{poolId}
        method: delete
        cors: true
        authorizer: aws_iam

  billing:
    handler: api/billing/billing.main
    events:
    - http:
        path: billing
        method: post
        cors: true
        authorizer: aws_iam

resources:
# API Gateway Errors
- ${file(resources/api-gateway-errors.yml)}
# DynamoDB
- ${file(resources/dynamodb-table.yml)}
# S3
- ${file(resources/s3-bucket.yml)}
# Cognito
- ${file(resources/cognito-user-pool.yml)}
- ${file(resources/cognito-identity-pool.yml)}
