Resources:
#  WebsocketConnectionsTable:
#    Type: AWS::DynamoDB::Table
#    Properties:
#      TableName: ${self:custom.websocketConnectionsTableName}
#      AttributeDefinitions:
#      - AttributeName: keyId
#        AttributeType: S
#      - AttributeName: connectionId
#        AttributeType: S
#      KeySchema:
#      - AttributeName: keyId
#        KeyType: HASH
#      - AttributeName: connectionId
#        KeyType: RANGE
#      BillingMode: PAY_PER_REQUEST
  OpenTokEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.openTokEventsTableName}
      AttributeDefinitions:
      - AttributeName: eventId
        AttributeType: S
      KeySchema:
      - AttributeName: eventId
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  UserProfilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.userProfilesTableName}
      AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      KeySchema:
      - AttributeName: userId
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  PoolsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.poolsTableName}
      AttributeDefinitions:
      - AttributeName: tenantId
        AttributeType: S
      - AttributeName: poolId
        AttributeType: S
      KeySchema:
      - AttributeName: tenantId
        KeyType: HASH
      - AttributeName: poolId
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  StreamsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.streamsTableName}
      AttributeDefinitions:
      - AttributeName: poolId
        AttributeType: S
      - AttributeName: streamId
        AttributeType: S
      KeySchema:
      - AttributeName: poolId
        KeyType: HASH
      - AttributeName: streamId
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST