Resources:
  ConnectionsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # see DynamoDBConnectionManager
      TableName: ${self:custom.graphqlWebsocketConnectionsTableName}
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      # connection id
      - AttributeName: id
        KeyType: HASH

  SubscriptionsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # see DynamoDBSubscriptionManager
      TableName: ${self:custom.graphqlWebsocketSubscriptionsTableName}
      AttributeDefinitions:
      - AttributeName: event
        AttributeType: S
      - AttributeName: subscriptionId
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      - AttributeName: event
        KeyType: HASH
      - AttributeName: subscriptionId
        KeyType: RANGE

  SubscriptionOperationsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # see DynamoDBSubscriptionManager
      TableName: ${self:custom.graphqlWebsocketSubscriptionOperationsTableName}
      AttributeDefinitions:
      - AttributeName: subscriptionId
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      - AttributeName: subscriptionId
        KeyType: HASH

  EventsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # see DynamoDBEventStore
      TableName: ${self:custom.graphqlWebsocketEventsTableName}
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      # see ISubscriptionEvent
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      StreamSpecification:
        StreamViewType: NEW_IMAGE